name: Build and Push OCI Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: bootc-test
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    
    container:
      image: quay.io/fedora/fedora:44
      options: --privileged
      
    permissions:
      contents: read
      packages: write

    steps:
      - name: Install dependencies
        run: dnf install --setopt=install_weak_deps=False -y buildah podman

      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Build Image with Buildah Action
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
          extra-args: |
            --cap-add=SYS_ADMIN

      - name: Log in to the GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /run/containers/0/auth.json

      - name: Push to GitHub Container Registry
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          extra-args: |
            --authfile=/run/containers/0/auth.json

      - name: Print image URL
        run: echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
